import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from '../../services/axiosInstance';
import { toast } from 'react-toastify';
import styles from './ResumeList.module.css';

const ResumeList = () => {
  const [resumes, setResumes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchResumes = useCallback(async () => {
    try {
      setLoading(true);
      const response = await axios.get('/api/resumes');
      setResumes(response.data || []);
      setError(null);
    } catch (err) {
      console.error(err);
      const message = err?.response?.data?.message || 'Failed to load resumes.';
      setError(message);
      toast.error(message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchResumes();
  }, [fetchResumes]);

  const renderStatus = (resume) => {
    const status = resume.generationStatus || 'pending';
    if (status === 'completed') return 'Ready';
    if (status === 'failed') return 'Failed';
    if (status === 'processing') return 'Generating...';
    return 'Pending';
  };

  const formatDate = (value) => {
    if (!value) return '—';
    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) {
      return '—';
    }
    return parsed.toLocaleString();
  };

  if (loading) {
    return (
      <div className={styles.stateCard}>
        <div className={styles.spinner} />
        <p>Fetching your resumes...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles.stateCard}>
        <p>{error}</p>
        <button className={styles.primaryBtn} onClick={fetchResumes}>
          Retry
        </button>
      </div>
    );
  }

  if (!resumes.length) {
    return (
      <div className={styles.stateCard}>
        <h3>No resumes yet</h3>
        <p>Create your first resume to see it here.</p>
        <Link className={styles.primaryBtn} to="/home">
          Build a Resume
        </Link>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <div>
          <h2>My AI Resumes</h2>
          <p>Download ATS-friendly PDFs generated by your selected AI.</p>
        </div>
        <button className={styles.secondaryBtn} onClick={fetchResumes}>
          Refresh
        </button>
      </div>

      <div className={styles.list}>
        {resumes.map((resume) => {
          const provider =
            resume.lastGenerationProvider ||
            resume.aiSettings?.provider ||
            'openai';
          const suggestions = resume.latestSuggestions || [];
          const downloadDisabled =
            resume.generationStatus !== 'completed' || !resume.latestPdfUrl;
          const lastGeneratedAt =
            resume.aiGeneratedVersions?.[resume.aiGeneratedVersions.length - 1]?.createdAt ||
            resume.updatedAt ||
            resume.createdAt;

          return (
            <div key={resume._id} className={styles.card}>
              <div className={styles.cardBody}>
                <h3>{resume.personalInfo?.fullName || 'Untitled Resume'}</h3>
                <p className={styles.meta}>
                  Status: <span className={styles.status}>{renderStatus(resume)}</span>
                </p>
                <p className={styles.meta}>
                  AI Engine: {provider === 'gemini' ? 'Google Gemini 1.5' : 'OpenAI GPT-4o Mini'}
                </p>
                <p className={styles.meta}>
                  Last generated: {formatDate(lastGeneratedAt)}
                </p>
                {suggestions.length > 0 && (
                  <div className={styles.suggestions}>
                    <p>Suggestions:</p>
                    <ul>
                      {suggestions.slice(0, 3).map((tip, idx) => (
                        <li key={idx}>{tip}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
              <div className={styles.cardActions}>
                <Link className={styles.secondaryBtn} to="/home">
                  Edit
                </Link>
                <a
                  href={downloadDisabled ? undefined : resume.latestPdfUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={`${styles.primaryBtn} ${
                    downloadDisabled ? styles.disabledBtn : ''
                  }`}
                  onClick={(event) => {
                    if (downloadDisabled) {
                      event.preventDefault();
                    }
                  }}
                  aria-disabled={downloadDisabled}
                >
                  {resume.generationStatus === 'completed' ? 'Download PDF' : 'Generating...'}
                </a>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default ResumeList;